import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

const recipes = [
  {id:"seed_lurou_fan",name:"台式卤肉饭",description:"浓郁酱香，肥瘦相间",tags:["家常菜","主食","下饭菜","盖饭"],time:"60分钟",difficulty:"中等",calories:"450kcal",steps:["五花肉切小丁","热油爆香红葱头","加入肉丁炒至变色","加酱油冰糖五香粉","小火炖40分钟","浇在白米饭上"],ingredients_missing:[{name:"五花肉",amount:"300g"},{name:"酱油",amount:"3勺"},{name:"冰糖",amount:"适量"},{name:"红葱头",amount:"5个"},{name:"五香粉",amount:"少许"},{name:"大米",amount:"2杯"}]},
  {id:"seed_gongbao_jiding",name:"宫保鸡丁",description:"酸甜微辣，花生酥香",tags:["家常菜","快手菜","下饭菜","川菜"],time:"25分钟",difficulty:"简单",calories:"380kcal",steps:["鸡胸肉切丁加料酒生抽腌制","调好糖醋酱汁备用","热油炒香干辣椒和花椒","下鸡丁翻炒至断生","加入黄瓜丁和花生米","倒入酱汁收浓即可"],ingredients_missing:[{name:"鸡胸肉",amount:"250g"},{name:"花生米",amount:"50g"},{name:"黄瓜",amount:"1根"},{name:"干辣椒",amount:"6个"},{name:"花椒",amount:"1小勺"},{name:"生抽",amount:"2勺"}]},
  {id:"seed_yuxiang_rusi",name:"鱼香肉丝",description:"咸鲜酸甜，超级下饭",tags:["家常菜","下饭菜","川菜","快手菜"],time:"30分钟",difficulty:"中等",calories:"360kcal",steps:["猪里脊切丝腌制","木耳胡萝卜青椒切丝","调鱼香汁备用","热锅滑炒肉丝盛出","下配菜炒软","倒回肉丝和酱汁快速翻匀"],ingredients_missing:[{name:"猪里脊",amount:"200g"},{name:"木耳",amount:"30g"},{name:"胡萝卜",amount:"1根"},{name:"青椒",amount:"1个"},{name:"豆瓣酱",amount:"1勺"},{name:"醋",amount:"1勺"}]},
  {id:"seed_shuizhu_niurou",name:"水煮牛肉",description:"麻辣浓烈，香气扑鼻",tags:["硬菜","川菜","麻辣","下饭菜"],time:"45分钟",difficulty:"中等",calories:"520kcal",steps:["牛肉切片加淀粉蛋清抓匀","豆芽和生菜焯熟垫底","炒香豆瓣酱和辣椒","加水煮开调味","下牛肉片滑熟","撒蒜末辣椒面浇热油激香"],ingredients_missing:[{name:"牛里脊",amount:"300g"},{name:"豆芽",amount:"200g"},{name:"生菜",amount:"150g"},{name:"郫县豆瓣酱",amount:"2勺"},{name:"干辣椒",amount:"10个"},{name:"花椒",amount:"1勺"}]},
  {id:"seed_lajiao_chaorou",name:"辣椒炒肉",description:"香辣过瘾，经典湘味",tags:["湘菜","家常菜","下饭菜","麻辣"],time:"20分钟",difficulty:"简单",calories:"410kcal",steps:["五花肉切薄片","青红椒切块","热锅煸炒五花肉出油","加入蒜片豆豉爆香","倒入辣椒翻炒","加生抽盐调味即可"],ingredients_missing:[{name:"五花肉",amount:"250g"},{name:"青椒",amount:"3个"},{name:"红椒",amount:"1个"},{name:"蒜",amount:"4瓣"},{name:"豆豉",amount:"1勺"},{name:"生抽",amount:"2勺"}]},
  {id:"seed_duojiao_yutou",name:"剁椒鱼头",description:"鲜辣开胃，宴客硬菜",tags:["湘菜","硬菜","蒸菜","下饭菜"],time:"50分钟",difficulty:"中等",calories:"430kcal",steps:["鱼头洗净铺姜片","表面抹料酒和盐腌制","铺满剁椒和蒜末","水开后上锅蒸15分钟","取出淋蒸鱼豉油","浇热油撒葱花即可"],ingredients_missing:[{name:"鱼头",amount:"1个"},{name:"剁椒",amount:"4勺"},{name:"姜",amount:"6片"},{name:"蒜",amount:"5瓣"},{name:"蒸鱼豉油",amount:"2勺"},{name:"葱",amount:"2根"}]},
  {id:"seed_xihongshi_chaodan",name:"西红柿炒蛋",description:"酸甜柔嫩，国民家常菜",tags:["家常菜","快手菜","下饭菜","清淡"],time:"15分钟",difficulty:"简单",calories:"220kcal",steps:["番茄切块鸡蛋打散","鸡蛋先炒熟盛出","番茄下锅炒出汁","加少许糖和盐调味","倒回鸡蛋翻炒","收汁后装盘即可"],ingredients_missing:[{name:"番茄",amount:"2个"},{name:"鸡蛋",amount:"3个"},{name:"盐",amount:"适量"},{name:"糖",amount:"1小勺"},{name:"食用油",amount:"适量"}]},
  {id:"seed_mapo_tofu",name:"麻婆豆腐",description:"麻辣鲜香，拌饭一绝",tags:["川菜","麻辣","家常菜","下饭菜"],time:"20分钟",difficulty:"简单",calories:"260kcal",steps:["豆腐切块焯水","牛肉末炒香","加入豆瓣酱和蒜末炒出红油","加少量清水煮开","放入豆腐小火炖煮","勾芡后撒花椒粉和葱花"],ingredients_missing:[{name:"嫩豆腐",amount:"1盒"},{name:"牛肉末",amount:"80g"},{name:"郫县豆瓣酱",amount:"1勺"},{name:"蒜",amount:"3瓣"},{name:"淀粉",amount:"1勺"},{name:"花椒粉",amount:"少许"}]},
  {id:"seed_danchaofan",name:"扬州炒饭",description:"粒粒分明，鲜香丰富",tags:["主食","炒饭","快手菜","家常菜"],time:"20分钟",difficulty:"简单",calories:"430kcal",steps:["隔夜饭打散","鸡蛋炒碎盛出","虾仁火腿胡萝卜切丁","热锅炒香配料","加入米饭翻炒均匀","倒回鸡蛋调味炒匀"],ingredients_missing:[{name:"米饭",amount:"2碗"},{name:"鸡蛋",amount:"2个"},{name:"虾仁",amount:"80g"},{name:"火腿",amount:"60g"},{name:"胡萝卜",amount:"50g"},{name:"青豆",amount:"50g"}]},
  {id:"seed_niurou_mian",name:"红烧牛肉面",description:"汤浓肉烂，暖胃满足",tags:["主食","面条","汤羹","硬菜"],time:"90分钟",difficulty:"中等",calories:"560kcal",steps:["牛腩焯水备用","炒香葱姜蒜和豆瓣酱","加入牛腩翻炒上色","加水炖煮至软烂","另起锅煮面","将牛肉和汤浇在面上"],ingredients_missing:[{name:"牛腩",amount:"400g"},{name:"面条",amount:"2份"},{name:"豆瓣酱",amount:"1勺"},{name:"八角",amount:"2个"},{name:"姜",amount:"5片"},{name:"小青菜",amount:"适量"}]},
  {id:"seed_haixian_yimian",name:"海鲜番茄意面",description:"酸香开胃，鲜味十足",tags:["西餐","意面","快手菜","主食"],time:"30分钟",difficulty:"中等",calories:"480kcal",steps:["意面煮至8分熟","虾仁和鱿鱼煎香","蒜末炒香后加入番茄酱","加入少量煮面水","放入意面和海鲜翻拌","撒黑胡椒和芝士粉"],ingredients_missing:[{name:"意大利面",amount:"200g"},{name:"虾仁",amount:"120g"},{name:"鱿鱼圈",amount:"100g"},{name:"番茄酱",amount:"4勺"},{name:"蒜",amount:"4瓣"},{name:"黑胡椒",amount:"少许"}]},
  {id:"seed_heijiao_niupai",name:"黑椒牛排",description:"肉香浓郁，西式经典",tags:["西餐","牛排","硬菜","高蛋白"],time:"25分钟",difficulty:"中等",calories:"520kcal",steps:["牛排提前回温撒盐黑胡椒","平底锅加黄油烧热","两面煎至喜欢熟度","加入蒜瓣和迷迭香增香","静置切片","搭配黑椒汁和时蔬食用"],ingredients_missing:[{name:"牛排",amount:"1块"},{name:"黑胡椒",amount:"适量"},{name:"海盐",amount:"适量"},{name:"黄油",amount:"15g"},{name:"蒜",amount:"2瓣"},{name:"迷迭香",amount:"1枝"}]},
  {id:"seed_jirou_shala",name:"烤鸡胸沙拉",description:"清爽低卡，轻负担饱腹",tags:["轻食","低卡","减脂","沙拉"],time:"20分钟",difficulty:"简单",calories:"280kcal",steps:["鸡胸肉撒盐黑胡椒煎熟","生菜番茄黄瓜切好","鸡蛋煮熟对半切","调油醋汁备用","将所有食材装盘","淋上酱汁拌匀即可"],ingredients_missing:[{name:"鸡胸肉",amount:"150g"},{name:"生菜",amount:"100g"},{name:"圣女果",amount:"8个"},{name:"黄瓜",amount:"1根"},{name:"鸡蛋",amount:"1个"},{name:"油醋汁",amount:"2勺"}]},
  {id:"seed_sanwenyu_shala",name:"烟熏三文鱼沙拉",description:"鲜嫩咸香，轻盈高级",tags:["西餐","轻食","沙拉","低卡"],time:"15分钟",difficulty:"简单",calories:"260kcal",steps:["生菜洗净沥干","牛油果切片","摆入烟熏三文鱼","加入玉米粒和紫甘蓝","调柠檬橄榄油汁","食用前拌匀即可"],ingredients_missing:[{name:"烟熏三文鱼",amount:"80g"},{name:"生菜",amount:"80g"},{name:"牛油果",amount:"1个"},{name:"玉米粒",amount:"50g"},{name:"紫甘蓝",amount:"50g"},{name:"柠檬",amount:"半个"}]},
  {id:"seed_zhaojiangmian",name:"老北京炸酱面",description:"酱香浓厚，面条筋道",tags:["主食","面条","家常菜","下饭菜"],time:"35分钟",difficulty:"中等",calories:"510kcal",steps:["猪肉末炒香","加入甜面酱和黄豆酱炒出香味","加少量水熬成炸酱","黄瓜胡萝卜切丝","面条煮熟过凉","淋上炸酱拌匀食用"],ingredients_missing:[{name:"面条",amount:"2份"},{name:"猪肉末",amount:"150g"},{name:"甜面酱",amount:"2勺"},{name:"黄豆酱",amount:"1勺"},{name:"黄瓜",amount:"1根"},{name:"胡萝卜",amount:"1根"}]},
  {id:"seed_rizhi_lamian",name:"日式豚骨拉面",description:"浓白汤底，暖心治愈",tags:["日料","面条","主食","汤羹"],time:"40分钟",difficulty:"中等",calories:"540kcal",steps:["拉面煮熟备用","豚骨汤底加热","叉烧切片煎香","溏心蛋对半切开","将面装入碗中","倒入热汤并铺上配菜"],ingredients_missing:[{name:"日式拉面",amount:"2份"},{name:"豚骨汤底",amount:"500ml"},{name:"叉烧肉",amount:"6片"},{name:"溏心蛋",amount:"2个"},{name:"海苔",amount:"2片"},{name:"玉米粒",amount:"50g"}]},
  {id:"seed_zhaoshao_jifan",name:"照烧鸡排饭",description:"咸甜焦香，便当常客",tags:["日料","盖饭","主食","家常菜"],time:"25分钟",difficulty:"简单",calories:"470kcal",steps:["鸡腿排去骨煎至两面金黄","加入照烧汁焖至入味","西兰花胡萝卜焯熟","米饭装碗","鸡排切条铺在饭上","淋上剩余酱汁即可"],ingredients_missing:[{name:"鸡腿排",amount:"2块"},{name:"照烧汁",amount:"3勺"},{name:"大米",amount:"2杯"},{name:"西兰花",amount:"100g"},{name:"胡萝卜",amount:"50g"}]},
  {id:"seed_sushi_pinjian",name:"三文鱼寿司拼盘",description:"清新鲜美，颜值在线",tags:["日料","寿司","轻食","低卡"],time:"40分钟",difficulty:"中等",calories:"320kcal",steps:["寿司饭加寿司醋拌匀放凉","三文鱼切片","黄瓜和牛油果切条","竹帘铺海苔和米饭","卷入配料卷紧切段","搭配芥末和酱油食用"],ingredients_missing:[{name:"三文鱼",amount:"150g"},{name:"寿司米",amount:"2碗"},{name:"海苔",amount:"4张"},{name:"黄瓜",amount:"1根"},{name:"牛油果",amount:"1个"},{name:"寿司醋",amount:"3勺"}]},
  {id:"seed_bibimbap",name:"韩式石锅拌饭",description:"酱香微辣，食材丰富",tags:["韩餐","主食","盖饭","下饭菜"],time:"35分钟",difficulty:"中等",calories:"530kcal",steps:["各类蔬菜焯熟调味","牛肉丝炒香","石锅刷油铺米饭","依次码上蔬菜和牛肉","放入煎蛋","拌入韩式辣酱后食用"],ingredients_missing:[{name:"米饭",amount:"2碗"},{name:"牛肉丝",amount:"120g"},{name:"菠菜",amount:"80g"},{name:"胡萝卜",amount:"50g"},{name:"豆芽",amount:"100g"},{name:"韩式辣酱",amount:"2勺"}]},
  {id:"seed_budae_jjigae",name:"韩式部队锅",description:"热辣丰盛，宵夜聚餐首选",tags:["韩餐","麻辣","宵夜","汤羹"],time:"30分钟",difficulty:"简单",calories:"560kcal",steps:["锅中铺入午餐肉年糕泡面等食材","加入泡菜和金针菇","调入韩式辣酱和高汤","大火煮开","面饼煮软后加芝士","融化后即可食用"],ingredients_missing:[{name:"午餐肉",amount:"150g"},{name:"泡菜",amount:"150g"},{name:"年糕",amount:"100g"},{name:"方便面",amount:"1块"},{name:"韩式辣酱",amount:"2勺"},{name:"芝士片",amount:"2片"}]},
  {id:"seed_qingzheng_cod",name:"清蒸鳕鱼",description:"鲜嫩少油，清爽不腻",tags:["蒸菜","清淡","高蛋白","低卡"],time:"20分钟",difficulty:"简单",calories:"190kcal",steps:["鳕鱼解冻擦干","铺姜丝和葱段腌10分钟","水开后上锅蒸8分钟","倒掉多余汤汁","淋蒸鱼豉油","浇热油激香即可"],ingredients_missing:[{name:"鳕鱼",amount:"200g"},{name:"姜",amount:"4片"},{name:"葱",amount:"2根"},{name:"蒸鱼豉油",amount:"2勺"},{name:"食用油",amount:"少许"}]},
  {id:"seed_xilanhua_xiaren",name:"西兰花炒虾仁",description:"清爽鲜甜，减脂友好",tags:["轻食","高蛋白","低卡","快手菜"],time:"18分钟",difficulty:"简单",calories:"230kcal",steps:["虾仁加料酒胡椒腌制","西兰花焯水备用","蒜末爆香后下虾仁","炒至变色加入西兰花","加盐和少量蚝油","翻匀后出锅"],ingredients_missing:[{name:"虾仁",amount:"180g"},{name:"西兰花",amount:"200g"},{name:"蒜",amount:"3瓣"},{name:"蚝油",amount:"1勺"},{name:"料酒",amount:"1勺"}]},
  {id:"seed_jidan_geng",name:"虾皮蒸蛋羹",description:"口感细嫩，清淡鲜美",tags:["蒸菜","清淡","早餐","辅食"],time:"15分钟",difficulty:"简单",calories:"120kcal",steps:["鸡蛋打散加入温水","过筛倒入碗中","撒少量虾皮","盖保鲜膜扎孔","上锅蒸10分钟","淋少许香油和酱油"],ingredients_missing:[{name:"鸡蛋",amount:"2个"},{name:"温水",amount:"200ml"},{name:"虾皮",amount:"1小勺"},{name:"香油",amount:"少许"},{name:"生抽",amount:"少许"}]},
  {id:"seed_nan_gua_zhou",name:"南瓜小米粥",description:"香甜软糯，暖胃早餐",tags:["早餐","清淡","儿童餐","辅食"],time:"35分钟",difficulty:"简单",calories:"160kcal",steps:["南瓜去皮切小块","小米淘洗干净","南瓜和小米一起入锅","加足量清水煮开","转小火熬煮20分钟","搅拌至浓稠即可"],ingredients_missing:[{name:"南瓜",amount:"200g"},{name:"小米",amount:"80g"},{name:"清水",amount:"800ml"}]},
  {id:"seed_jianjiao_tudousi",name:"尖椒土豆丝",description:"脆爽开胃，经典下饭",tags:["家常菜","快手菜","下饭菜","清淡"],time:"15分钟",difficulty:"简单",calories:"180kcal",steps:["土豆切丝泡水去淀粉","尖椒切丝","热锅爆香蒜末","下土豆丝大火翻炒","加入尖椒和醋","调盐后炒至断生"],ingredients_missing:[{name:"土豆",amount:"2个"},{name:"尖椒",amount:"2个"},{name:"蒜",amount:"3瓣"},{name:"醋",amount:"1勺"},{name:"盐",amount:"适量"}]},
  {id:"seed_dongyin_gong",name:"冬阴功海鲜汤",description:"酸辣鲜爽，泰式风味",tags:["汤羹","麻辣","西餐","轻食"],time:"30分钟",difficulty:"中等",calories:"210kcal",steps:["锅中煮开高汤","加入香茅南姜和柠檬叶","放入虾和蛤蜊","加入蘑菇和番茄","调入冬阴功酱和鱼露","最后加椰浆和青柠汁"],ingredients_missing:[{name:"虾",amount:"120g"},{name:"蛤蜊",amount:"150g"},{name:"蘑菇",amount:"100g"},{name:"冬阴功酱",amount:"2勺"},{name:"椰浆",amount:"100ml"},{name:"青柠",amount:"1个"}]},
  {id:"seed_luojifen",name:"螺蛳粉",description:"酸辣浓郁，夜宵灵魂",tags:["主食","宵夜","小吃","麻辣"],time:"20分钟",difficulty:"简单",calories:"480kcal",steps:["米粉煮软捞出","酸笋木耳花生备好","锅中煮开汤底","加入米粉和配料","煮2分钟入味","撒葱花和辣油食用"],ingredients_missing:[{name:"螺蛳粉米粉",amount:"1包"},{name:"酸笋",amount:"50g"},{name:"木耳",amount:"30g"},{name:"花生米",amount:"20g"},{name:"腐竹",amount:"30g"},{name:"辣油",amount:"适量"}]},
  {id:"seed_jianbing_guozi",name:"煎饼果子",description:"外酥里软，早餐人气王",tags:["早餐","小吃","快手菜","主食"],time:"20分钟",difficulty:"中等",calories:"350kcal",steps:["面糊摊成薄饼","打入鸡蛋摊匀","撒葱花芝麻","翻面刷甜面酱和辣酱","放入薄脆和生菜","卷起切段即可"],ingredients_missing:[{name:"面粉",amount:"100g"},{name:"鸡蛋",amount:"2个"},{name:"甜面酱",amount:"2勺"},{name:"辣酱",amount:"1勺"},{name:"薄脆",amount:"2片"},{name:"生菜",amount:"2片"}]},
  {id:"seed_xiaolongbao",name:"鲜肉小笼包",description:"皮薄汁多，经典点心",tags:["早餐","小吃","家常菜","儿童餐"],time:"70分钟",difficulty:"困难",calories:"390kcal",steps:["面团发酵备用","猪肉馅加入皮冻拌匀","擀皮包入馅料","收口捏褶","蒸笼铺好防粘","上锅蒸10分钟即可"],ingredients_missing:[{name:"中筋面粉",amount:"300g"},{name:"猪肉馅",amount:"250g"},{name:"皮冻",amount:"100g"},{name:"酵母",amount:"3g"},{name:"姜末",amount:"适量"},{name:"生抽",amount:"2勺"}]},
  {id:"seed_suanla_tudousi",name:"酸辣土豆丝",description:"酸爽脆嫩，家常万能菜",tags:["家常菜","快手菜","下饭菜","凉菜"],time:"15分钟",difficulty:"简单",calories:"170kcal",steps:["土豆切细丝泡水","干辣椒剪段","热锅下油爆香辣椒","倒入土豆丝快速翻炒","加入白醋和盐","炒至断生即可"],ingredients_missing:[{name:"土豆",amount:"2个"},{name:"干辣椒",amount:"4个"},{name:"白醋",amount:"1.5勺"},{name:"盐",amount:"适量"},{name:"蒜",amount:"2瓣"}]},
  {id:"seed_kouliangpi",name:"麻酱凉皮",description:"爽滑筋道，夏日开胃",tags:["凉菜","小吃","主食","快手菜"],time:"15分钟",difficulty:"简单",calories:"320kcal",steps:["凉皮切条装盘","黄瓜切丝铺上","芝麻酱加水调开","加入蒜水和醋","淋在凉皮上","撒辣椒油和花生碎"],ingredients_missing:[{name:"凉皮",amount:"2份"},{name:"黄瓜",amount:"1根"},{name:"芝麻酱",amount:"2勺"},{name:"蒜",amount:"3瓣"},{name:"香醋",amount:"2勺"},{name:"辣椒油",amount:"适量"}]},
  {id:"seed_ziyuan_tangshui",name:"酒酿小圆子",description:"甜香软糯，暖心糖水",tags:["甜品","糖水","下午茶","小食"],time:"20分钟",difficulty:"简单",calories:"240kcal",steps:["锅中加水煮开","放入小圆子煮至浮起","加入酒酿和枸杞","打入鸡蛋花","加糖调味","小火再煮2分钟即可"],ingredients_missing:[{name:"小圆子",amount:"150g"},{name:"酒酿",amount:"100g"},{name:"鸡蛋",amount:"1个"},{name:"枸杞",amount:"少许"},{name:"冰糖",amount:"适量"}]},
  {id:"seed_mangguo_yangzhi",name:"杨枝甘露",description:"果香浓郁，冰爽顺滑",tags:["甜品","糖水","下午茶","饮品"],time:"25分钟",difficulty:"简单",calories:"280kcal",steps:["芒果切丁留一部分装饰","西米煮熟过凉","芒果和椰浆牛奶打成泥","加入西米和西柚粒","放冰箱冷藏","食用前加芒果丁即可"],ingredients_missing:[{name:"芒果",amount:"2个"},{name:"西米",amount:"50g"},{name:"椰浆",amount:"100ml"},{name:"牛奶",amount:"150ml"},{name:"西柚",amount:"半个"}]},
  {id:"seed_tiramisu",name:"提拉米苏",description:"咖啡香浓，绵密微苦",tags:["甜品","蛋糕","下午茶","西餐"],time:"40分钟",difficulty:"中等",calories:"360kcal",steps:["马斯卡彭和淡奶油打发","手指饼蘸咖啡液","铺一层饼干一层奶酪糊","重复叠放","冷藏4小时定型","表面筛可可粉"],ingredients_missing:[{name:"马斯卡彭",amount:"250g"},{name:"淡奶油",amount:"200ml"},{name:"手指饼干",amount:"1包"},{name:"浓缩咖啡",amount:"80ml"},{name:"可可粉",amount:"适量"}]},
  {id:"seed_basu_cheesecake",name:"巴斯克芝士蛋糕",description:"焦香浓郁，入口绵滑",tags:["甜品","蛋糕","下午茶","小食"],time:"50分钟",difficulty:"中等",calories:"390kcal",steps:["奶油奶酪软化搅匀","加入糖和鸡蛋搅拌","倒入淡奶油和玉米淀粉","模具垫纸倒入面糊","高温烘烤至表面焦糖色","冷藏后切块食用"],ingredients_missing:[{name:"奶油奶酪",amount:"250g"},{name:"鸡蛋",amount:"2个"},{name:"细砂糖",amount:"60g"},{name:"淡奶油",amount:"120ml"},{name:"玉米淀粉",amount:"10g"}]},
  {id:"seed_hongdou_shuangpi",name:"红豆双皮奶",description:"奶香细腻，甜而不腻",tags:["甜品","糖水","下午茶","小食"],time:"35分钟",difficulty:"简单",calories:"220kcal",steps:["牛奶煮热倒入碗中放凉结皮","鸡蛋清加糖打匀","挑起奶皮倒出牛奶","牛奶倒入蛋清液混匀","重新倒回碗中保留奶皮","蒸15分钟后加蜜红豆"],ingredients_missing:[{name:"纯牛奶",amount:"300ml"},{name:"鸡蛋清",amount:"2个"},{name:"细砂糖",amount:"20g"},{name:"蜜红豆",amount:"40g"}]},
  {id:"seed_zhenzhu_naicha",name:"黑糖珍珠奶茶",description:"Q弹香甜，经典奶茶店风味",tags:["饮品","奶茶","下午茶","小食"],time:"30分钟",difficulty:"简单",calories:"340kcal",steps:["珍珠煮熟焖透","黑糖加少量水熬成糖浆","杯壁挂上黑糖","红茶泡浓后放凉","加入牛奶和冰块","倒入珍珠即可"],ingredients_missing:[{name:"珍珠粉圆",amount:"80g"},{name:"黑糖",amount:"40g"},{name:"红茶包",amount:"2个"},{name:"牛奶",amount:"250ml"},{name:"冰块",amount:"适量"}]},
  {id:"seed_chengzi_guozhi",name:"鲜橙胡萝卜汁",description:"清甜爽口，维C满满",tags:["饮品","果汁","轻食","低卡"],time:"10分钟",difficulty:"简单",calories:"110kcal",steps:["橙子去皮切块","胡萝卜切小块","加入少量凉开水","放入榨汁机打匀","过滤或直接饮用","冷藏后口感更佳"],ingredients_missing:[{name:"橙子",amount:"2个"},{name:"胡萝卜",amount:"1根"},{name:"凉开水",amount:"100ml"}]},
  {id:"seed_molihua_guocha",name:"茉莉葡萄茶",description:"花香果甜，清爽解腻",tags:["饮品","茶饮","果汁","下午茶"],time:"15分钟",difficulty:"简单",calories:"90kcal",steps:["茉莉花茶泡好放凉","葡萄去皮去籽捣碎","杯中加入冰块和葡萄果肉","倒入茶底","加少许蜂蜜调味","搅匀即可饮用"],ingredients_missing:[{name:"茉莉花茶",amount:"300ml"},{name:"葡萄",amount:"120g"},{name:"蜂蜜",amount:"1勺"},{name:"冰块",amount:"适量"}]},
  {id:"seed_mojito",name:"青柠莫吉托",description:"清新微醺，薄荷感十足",tags:["鸡尾酒","调酒","酒饮","微醺"],time:"10分钟",difficulty:"简单",calories:"160kcal",steps:["杯中放青柠块和薄荷叶","加入糖浆轻轻捣压","倒入朗姆酒","加满冰块","补入苏打水","轻轻搅拌即可"],ingredients_missing:[{name:"白朗姆酒",amount:"45ml"},{name:"青柠",amount:"1个"},{name:"薄荷叶",amount:"8片"},{name:"糖浆",amount:"15ml"},{name:"苏打水",amount:"120ml"},{name:"冰块",amount:"适量"}]},
  {id:"seed_tequila_sunrise",name:"龙舌兰日出",description:"色彩层次分明，果香微醺",tags:["鸡尾酒","调酒","酒饮","微醺"],time:"8分钟",difficulty:"简单",calories:"180kcal",steps:["杯中加入冰块","倒入龙舌兰和橙汁","轻轻搅匀","沿杯壁缓缓倒入红石榴糖浆","形成渐层效果","用橙片装饰即可"],ingredients_missing:[{name:"龙舌兰",amount:"45ml"},{name:"橙汁",amount:"120ml"},{name:"红石榴糖浆",amount:"10ml"},{name:"冰块",amount:"适量"},{name:"橙片",amount:"1片"}]},
  {id:"seed_hotpot_feiniu",name:"番茄肥牛锅",description:"酸香开胃，热乎满足",tags:["汤羹","硬菜","下饭菜","家常菜"],time:"25分钟",difficulty:"简单",calories:"460kcal",steps:["番茄炒软出汁","加入清水或高汤煮开","放入金针菇和娃娃菜","加入肥牛卷煮熟","调入盐和番茄酱","撒葱花即可上桌"],ingredients_missing:[{name:"肥牛卷",amount:"250g"},{name:"番茄",amount:"3个"},{name:"金针菇",amount:"150g"},{name:"娃娃菜",amount:"1颗"},{name:"番茄酱",amount:"2勺"},{name:"高汤",amount:"500ml"}]},
  {id:"seed_paigu_luobotang",name:"萝卜排骨汤",description:"清甜鲜香，家常暖胃",tags:["汤羹","家常菜","清淡","高蛋白"],time:"70分钟",difficulty:"简单",calories:"260kcal",steps:["排骨焯水洗净","白萝卜切块","砂锅中放排骨和姜片","加足量清水炖40分钟","加入萝卜继续煮20分钟","加盐调味撒葱花"],ingredients_missing:[{name:"排骨",amount:"400g"},{name:"白萝卜",amount:"1根"},{name:"姜",amount:"4片"},{name:"葱",amount:"1根"},{name:"盐",amount:"适量"}]},
  {id:"seed_liangban_huanggua",name:"蒜泥凉拌黄瓜",description:"清脆爽口，解腻必备",tags:["凉菜","快手菜","清淡","低卡"],time:"10分钟",difficulty:"简单",calories:"70kcal",steps:["黄瓜拍碎切段","蒜切末","加盐稍微腌一下黄瓜","倒掉多余水分","加入蒜末生抽醋和香油","拌匀后冷藏片刻"],ingredients_missing:[{name:"黄瓜",amount:"2根"},{name:"蒜",amount:"4瓣"},{name:"生抽",amount:"1勺"},{name:"香醋",amount:"1勺"},{name:"香油",amount:"少许"},{name:"盐",amount:"适量"}]},
  {id:"seed_kou_shui_ji",name:"口水鸡",description:"麻辣鲜香，凉菜中的硬角色",tags:["凉菜","川菜","麻辣","高蛋白"],time:"35分钟",difficulty:"中等",calories:"320kcal",steps:["鸡腿冷水下锅煮熟","捞出冰水浸泡后切块","调制红油蒜泥麻酱汁","鸡块摆盘","淋上料汁","撒花生碎和香菜即可"],ingredients_missing:[{name:"鸡腿",amount:"2只"},{name:"辣椒油",amount:"2勺"},{name:"花椒油",amount:"1勺"},{name:"蒜",amount:"4瓣"},{name:"花生碎",amount:"20g"},{name:"香菜",amount:"适量"}]},
  {id:"seed_yeban_chaomian",name:"酱油炒面",description:"锅气十足，深夜超满足",tags:["宵夜","主食","面条","快手菜"],time:"15分钟",difficulty:"简单",calories:"420kcal",steps:["面条煮至七分熟","包菜胡萝卜切丝","热锅炒香蒜末","加入配菜翻炒","放入面条淋酱油老抽","大火翻匀出锅"],ingredients_missing:[{name:"面条",amount:"2份"},{name:"包菜",amount:"100g"},{name:"胡萝卜",amount:"50g"},{name:"蒜",amount:"3瓣"},{name:"生抽",amount:"2勺"},{name:"老抽",amount:"半勺"}]},
  {id:"seed_zhaji_niangao",name:"韩式炸鸡年糕",description:"甜辣黏香，追剧标配",tags:["韩餐","宵夜","小吃","麻辣"],time:"30分钟",difficulty:"中等",calories:"540kcal",steps:["鸡翅中裹粉炸至金黄","年糕煮软备用","锅中加韩式辣酱番茄酱和蜂蜜","下炸鸡和年糕翻匀","收汁裹满酱料","撒芝麻即可"],ingredients_missing:[{name:"鸡翅中",amount:"300g"},{name:"韩式年糕",amount:"150g"},{name:"韩式辣酱",amount:"2勺"},{name:"番茄酱",amount:"1勺"},{name:"蜂蜜",amount:"1勺"},{name:"淀粉",amount:"适量"}]},
  {id:"seed_turong_yumi",name:"奶香玉米烙",description:"香甜酥脆，老少都爱",tags:["小吃","甜品","儿童餐","下午茶"],time:"20分钟",difficulty:"中等",calories:"260kcal",steps:["玉米粒控干水分","拌入少量淀粉","平底锅铺底油加热","倒入玉米粒压平定型","煎至底部金黄酥脆","淋炼乳或撒糖食用"],ingredients_missing:[{name:"玉米粒",amount:"200g"},{name:"玉米淀粉",amount:"2勺"},{name:"炼乳",amount:"适量"},{name:"白糖",amount:"适量"},{name:"食用油",amount:"适量"}]},
  {id:"seed_tudou_nirou_ni",name:"土豆牛肉泥",description:"软糯细腻，宝宝也适合",tags:["辅食","儿童餐","高蛋白","清淡"],time:"30分钟",difficulty:"简单",calories:"170kcal",steps:["土豆去皮切块蒸熟","牛肉焯水后煮熟","将土豆和牛肉放入搅拌机","加入少量温水打成泥","回锅小火翻拌","温热后即可食用"],ingredients_missing:[{name:"土豆",amount:"150g"},{name:"牛里脊",amount:"80g"},{name:"温水",amount:"适量"}]},
  {id:"seed_sanwenyu_fan",name:"三文鱼饭团",description:"方便营养，儿童也喜欢",tags:["儿童餐","主食","早餐","日料"],time:"20分钟",difficulty:"简单",calories:"260kcal",steps:["三文鱼煎熟去刺捣碎","米饭加入少许盐和芝麻","拌入三文鱼碎","捏成三角饭团","外面包上海苔","可搭配番茄酱食用"],ingredients_missing:[{name:"三文鱼",amount:"100g"},{name:"米饭",amount:"2碗"},{name:"海苔",amount:"2张"},{name:"熟芝麻",amount:"1勺"},{name:"盐",amount:"少许"}]},
  {id:"seed_zheng_nangua_buding",name:"蒸南瓜布丁",description:"天然香甜，口感柔滑",tags:["辅食","甜品","蒸菜","儿童餐"],time:"25分钟",difficulty:"简单",calories:"140kcal",steps:["南瓜蒸熟压成泥","加入鸡蛋和牛奶搅匀","过筛倒入小碗","盖保鲜膜扎孔","上锅蒸12分钟","放温后即可食用"],ingredients_missing:[{name:"南瓜",amount:"150g"},{name:"鸡蛋",amount:"1个"},{name:"牛奶",amount:"80ml"}]},
  {id:"seed_jirou_shucai_bing",name:"鸡肉蔬菜饼",description:"软嫩好嚼，营养均衡",tags:["儿童餐","辅食","早餐","高蛋白"],time:"20分钟",difficulty:"简单",calories:"190kcal",steps:["鸡胸肉剁成泥","胡萝卜西兰花切碎焯熟","加入鸡蛋和面粉拌匀","平底锅刷油","舀入面糊摊成小饼","小火煎至两面熟透"],ingredients_missing:[{name:"鸡胸肉",amount:"100g"},{name:"胡萝卜",amount:"30g"},{name:"西兰花",amount:"30g"},{name:"鸡蛋",amount:"1个"},{name:"面粉",amount:"30g"}]},
  {id:"seed_shousi_jiroujuan",name:"鸡肉蔬菜卷",description:"清爽饱腹，便当友好",tags:["轻食","低卡","高蛋白","儿童餐"],time:"18分钟",difficulty:"简单",calories:"210kcal",steps:["鸡胸肉煎熟切条","生菜胡萝卜黄瓜切丝","饼皮微微加热","放入鸡肉和蔬菜","挤少量酸奶酱","卷紧后切段即可"],ingredients_missing:[{name:"鸡胸肉",amount:"120g"},{name:"全麦饼皮",amount:"2张"},{name:"生菜",amount:"4片"},{name:"黄瓜",amount:"1根"},{name:"胡萝卜",amount:"半根"},{name:"酸奶酱",amount:"2勺"}]},
  {id:"seed_congyou_banmian",name:"葱油拌面",description:"葱香浓郁，简单却上头",tags:["主食","面条","快手菜","宵夜"],time:"15分钟",difficulty:"简单",calories:"390kcal",steps:["小葱切段备用","锅中小火炸葱至焦黄","加入生抽老抽和糖煮开","面条煮熟捞出","淋上葱油汁","拌匀撒葱花即可"],ingredients_missing:[{name:"面条",amount:"2份"},{name:"小葱",amount:"1把"},{name:"生抽",amount:"2勺"},{name:"老抽",amount:"1勺"},{name:"白糖",amount:"1小勺"},{name:"食用油",amount:"适量"}]},
];

async function run() {
  const { data, error } = await supabase
    .from("recipes")
    .upsert(recipes, { onConflict: "id" })
    .select("id, name");

  if (error) {
    console.error("插入失败:", error.message);
  } else {
    console.log(`✅ 成功导入 ${data.length} 道菜谱（冲突的已更新）`);
  }

  const { count } = await supabase.from("recipes").select("*", { count: "exact", head: true });
  console.log(`数据库总计: ${count} 道菜谱`);
}

run();
